// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $('#background').on('tiler.goto', function(e, data) {
      var x, y;
      switch (data.enterTile.attr('id')) {
        case 'tile-1':
          x = 0;
          y = 100;
          break;
        case 'tile-2':
          x = 50;
          y = 100;
          break;
        case 'tile-3':
          x = 50;
          y = 50;
          break;
        case 'tile-4':
          x = 50;
          y = 0;
      }
      return $(this).closest('.tiler-viewport').css({
        backgroundPosition: "" + x + "% " + y + "%"
      });
    });
    $('.tiler-viewport').tiler();
    $('button[data-tiler-link]').each(function() {
      return $(this).text($(this).data('tiler-title'));
    });
    return $('button').click(function() {
      var tileId;
      tileId = $(this).data('tiler-link');
      return $(this).closest('.tiler-viewport').tiler('goTo', tileId);
    });
  });

}).call(this);
